China/routes/web.php
<?php

use App\Models\User;
use Illuminate\Support\Facades\Route;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group([
    'prefix' => 'user',
    'as' => 'user.',
    'namespace' => 'User',
    'middleware' => ['auth']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/event', 'HomeController@event')->name('adminevent');
    Route::resource('user', EventController::class);;
});

Route::group([
    'prefix' => 'admin',
    'as' => 'admin.',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'admin']
], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('admin', AdminController::class);
    Route::post('/event', 'EventController@Add');

    Route::get('/event', 'HomeController@event')->name('adminevent');
});

China/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

//    public function events()
//    {
//        return $this->belongsToMany(Event::class);
//    }
}

China/app/Http/Controllers/User/EventController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $contact = User::find($id);
        $contact->event = $request->get('event');
        $contact->save();

        return redirect('/user/event')->with('success', 'Contact updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

China/app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Event;
use App\Models\JoinEvent;
use App\Models\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index()
    {
        $user =  auth()-> user()->id;
        $users = User::all()->where('id',$user)->pluck('event');
        $event = Event::all()->wherein('event_id', $users);
        return view('user.home', compact('event'));
    }
    public function event()
    {
        $user =  auth()-> user()->id;
        $users = User::all()->where('id',$user);
//        $events = JoinEvent::pluck('event_id')->where('member_id', '=', $user);
        $user = User::all()->where('id',$user)->pluck('event');
        $event = Event::all()->whereNotIn('event_id', $user);
        return view('user.userevent', compact('event', 'users'));
    }

}

China/resources/views/user/home.blade.php
@extends('layouts.user')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h1>Registered Event</h1></div>

                    <div class="card-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>
{{--                                <td>ID</td>--}}
                                <td>Event</td>
                                <td>Date</td>
                                <td>Time</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($event as $events)
                                <tr>
{{--                                    <td>{{$loop->iteration}}</td>--}}
                                    <td>{{$events->title}}</td>
                                    <td>{{$events->date}}</td>
                                    <td>{{$events->start_time}} ~ {{$events->end_time}}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
@endsection

China/resources/views/user/userevent.blade.php
@extends('layouts.user')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"><h1>List Event</h1></div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <td>ID</td>
                                        <td>Event</td>
                                        <td>Date</td>
                                        <td>Time</td>
                                        <td colspan = 2>Actions</td>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($event as $events)
                                        <tr>
                                            <td>{{$loop->iteration}}</td>
                                        @foreach($users as $user)
                                            <td>{{$events->title}}</td>
                                            <td>{{$events->date}}</td>
                                            <td>{{$events->start_time}} ~ {{$events->end_time}}</td>
                                            <td>
                                                <form method="post" action="{{ route('user.user.update', $user->id) }}">
                                                    @csrf
                                                    @method('PUT')
                                                    <button class="btn btn-primary" style="background-color: #4BB543" type="submit"  name="event" value="{{$events->event_id}}">Join
                                                    </button>
                                                </form>
                                            </td>


                                        </tr>
                                        @endforeach
                                    @endforeach
                                    </tbody>
                                </table>
                                <div>
                                </div>

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
@endsection